# Pact provider workflow - dynamically fetches pacts, based on consumer version selectors
# Test (verify pacts) -> Publish verification results -> Can-I-Deploy to Prod -> Record Deployment (master branch)

pool:
  vmImage: ubuntu-latest

variables:
  - name: PACTICIPANT
    value: "pactflow-example-provider-dotnet"
  - name: PACT_BROKER_BASE_URL
    value: https://testdemo.pactflow.io
  - name: GIT_BRANCH
    value: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]
  - name: GIT_COMMIT
    value: $(Build.SourceVersion)
  - name: BUILD_URI
    value: '$(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)'

steps:
- script: |
    dotnet restore src
    dotnet restore tests
  displayName: 📦  Restore
- script: |
    dotnet run --project src &
  displayName: 🏁  Start Provider
- script: |
    dotnet test tests
  displayName: ✅  Test
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
    PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker can-i-deploy \
        --pacticipant ${PACTICIPANT} \
        --version ${GIT_COMMIT} \
        --to-environment production
  displayName: 🎛  Can I deploy?
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)

- script: |
    docker run \
      --rm \
      -v ${PWD}:${PWD} \
      -e PACT_BROKER_BASE_URL \
      -e PACT_BROKER_TOKEN pactfoundation/pact-cli:latest \
      broker record_deployment \
          --pacticipant ${PACTICIPANT} \
          --version ${GIT_COMMIT} \
          --environment production
  displayName: 🚀  Deploy
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)