# Pact provider workflow - dynamically fetches pacts, based on consumer version selectors
# Test (verify pacts) -> Publish verification results -> Can-I-Deploy to Prod -> Record Deployment (master branch)

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: pact_templates
      type: github
      name: you54f/azure-pipelines-templates
      endpoint: azure-templates-pact-github # azure service connection to allow read-only access to github repo
      # ref: refs/heads/templates # point to a commit / branch / tag

variables:
  - name: PACTICIPANT
    value: "pactflow-example-provider-dotnet"
  - name: PACT_BROKER_BASE_URL
    value: https://testdemo.pactflow.io
  - template: templates/azure_pact_variables.yml@pact_templates

steps:
- script: |
    dotnet restore src
    dotnet restore tests
  displayName: 📦  Restore
- script: |
    dotnet run --project src &
  displayName: 🏁  Start Provider
- script: |
    dotnet test tests
  displayName: ✅  Test
  env:
    PACT_BROKER_TOKEN: $(PACT_BROKER_TOKEN)
    PACT_BROKER_PUBLISH_VERIFICATION_RESULTS: true
    GIT_BRANCH: $(BRANCH)
    GIT_COMMIT: $(COMMIT)

- template: templates/azure_pact_can_i_deploy.yml@pact_templates
  parameters:
    to_environment: production
    application_name: $(PACTICIPANT)
    token: $(PACT_BROKER_TOKEN)
- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - template: templates/azure_pact_record_deployment.yml@pact_templates
    parameters:
      environment: production
      application_name: $(PACTICIPANT)
      token: $(PACT_BROKER_TOKEN)
